["Party 2 Is Hurt"] = {
    ["outline"] = "OUTLINE",
    ["iconSource"] = -1,
    ["wagoID"] = "xPU0qj4Ap",
    ["xOffset"] = 555.1951607840401,
    ["adjustedMax"] = "",
    ["customText"] = "function()\n    if not UnitClass(\"target\")  then return end\n    local col = RAID_CLASS_COLORS[select(2, UnitClass(\"target\"))].colorStr    \n    local cc,_,_,_ = GetUnitSpeed(\"target\")           \n    if not col or not cc then return end\n    \n    cc= string.format('%.0f',cc*100/BASE_MOVEMENT_SPEED)    \n    \n    if aura_env.config.n then \n        local m=GetUnitName('target')\n        return WrapTextInColorCode(m, col) ..cc    \n    else\n        return WrapTextInColorCode(cc, col) \n    end\nend\n--local col = RAID_CLASS_COLORS[select(2, UnitClass(\"target\"))].colorStr    \n--WrapTextInColorCode(cc, col) \n\n\n",
    ["yOffset"] = -150.5818120783026,
    ["anchorPoint"] = "CENTER",
    ["cooldownSwipe"] = true,
    ["config"] = {
    },
    ["customTextUpdate"] = "update",
    ["url"] = "https://wago.io/xPU0qj4Ap/1",
    ["actions"] = {
    ["start"] = {
    },
    ["init"] = {
    },
    ["finish"] = {
    },
    },
    ["triggers"] = {
    {
    ["trigger"] = {
    ["customVariables"] = "{}",
    ["type"] = "custom",
    ["custom_hide"] = "timed",
    ["subeventSuffix"] = "_CAST_START",
    ["unit"] = "player",
    ["duration"] = "1",
    ["event"] = "Health",
    ["use_unit"] = true,
    ["unevent"] = "auto",
    ["spellIds"] = {
    },
    ["custom"] = "function(allstates)\n    if not aura_env.last or GetTime() - aura_env.last > 0.5 then\n        aura_env.last = GetTime()\n        \n        local numGroup = GetNumGroupMembers()\n        if (numGroup < 3) then\n            allstates[\"\"] = allstates[\"\"] or {show = false}\n            allstates[\"\"].show = false\n            allstates[\"\"].changed = true\n            return true\n        end\n        \n        local hp,hpMax = UnitHealth(\"party2\"),UnitHealthMax(\"party2\")\n        \n        if (math.ceil((hp / hpMax) * 100) <= 60 and not UnitIsDead(\"party2\")) then\n            allstates[\"\"] = allstates[\"\"] or {show = true}\n            allstates[\"\"].changed = true\n            return true\n        else\n            allstates[\"\"] = allstates[\"\"] or {show = false}\n            allstates[\"\"].show = false\n            allstates[\"\"].changed = true\n            return true\n        end\n    end\nend\n\n\n\n",
    ["subeventPrefix"] = "SPELL",
    ["check"] = "update",
    ["names"] = {
    },
    ["custom_type"] = "stateupdate",
    ["debuffType"] = "HELPFUL",
    },
    ["untrigger"] = {
    ["custom"] = "function()\n    return not aura_env.isTriggered\nend",
    },
    },
    ["disjunctive"] = "all",
    ["activeTriggerMode"] = 1,
    },
    ["authorOptions"] = {
    },
    ["internalVersion"] = 78,
    ["keepAspectRatio"] = false,
    ["selfPoint"] = "BOTTOM",
    ["preferToUpdate"] = false,
    ["adjustedMin"] = "",
    ["shadowYOffset"] = -1,
    ["desaturate"] = false,
    ["parent"] = "Power, Health and Enemy Details",
    ["font"] = "聊天",
    ["version"] = 1,
    ["subRegions"] = {
    {
    ["type"] = "subbackground",
    },
    {
    ["text_text_format_p_time_precision"] = 1,
    ["text_text_format_s_format"] = "none",
    ["text_text"] = "%s",
    ["text_shadowColor"] = {
    0,
    0,
    0,
    1,
    },
    ["text_selfPoint"] = "AUTO",
    ["text_automaticWidth"] = "Auto",
    ["text_fixedWidth"] = 64,
    ["text_text_format_p_time_legacy_floor"] = false,
    ["text_justify"] = "CENTER",
    ["rotateText"] = "NONE",
    ["anchorYOffset"] = 0,
    ["type"] = "subtext",
    ["text_text_format_p_time_dynamic_threshold"] = 60,
    ["text_color"] = {
    1,
    1,
    1,
    1,
    },
    ["text_font"] = "Friz Quadrata TT",
    ["text_shadowXOffset"] = 0,
    ["text_shadowYOffset"] = 0,
    ["text_text_format_p_time_mod_rate"] = true,
    ["text_wordWrap"] = "WordWrap",
    ["text_fontType"] = "OUTLINE",
    ["text_anchorPoint"] = "CENTER",
    ["text_text_format_p_time_format"] = 0,
    ["text_visible"] = true,
    ["text_fontSize"] = 12,
    ["anchorXOffset"] = 0,
    ["text_text_format_p_format"] = "timed",
    },
    },
    ["height"] = 30,
    ["color"] = {
    0.96470588235294,
    0.89803921568627,
    0.91764705882353,
    1,
    },
    ["load"] = {
    ["use_level"] = false,
    ["talent"] = {
    ["multi"] = {
    },
    },
    ["level_operator"] = {
    "~=",
    },
    ["use_spellknown"] = false,
    ["size"] = {
    ["multi"] = {
    },
    },
    ["spec"] = {
    ["multi"] = {
    },
    },
    ["use_never"] = false,
    ["level"] = {
    "120",
    },
    ["class"] = {
    ["single"] = "WARLOCK",
    ["multi"] = {
    ["WARLOCK"] = true,
    },
    },
    ["zoneIds"] = "",
    },
    ["automaticWidth"] = "Auto",
    ["useAdjustededMax"] = false,
    ["fontSize"] = 13,
    ["source"] = "import",
    ["icon"] = true,
    ["shadowXOffset"] = 1,
    ["displayText"] = "%c",
    ["useTooltip"] = true,
    ["useAdjustededMin"] = false,
    ["regionType"] = "icon",
    ["progressSource"] = {
    -1,
    "",
    },
    ["animation"] = {
    ["start"] = {
    ["type"] = "none",
    ["easeStrength"] = 3,
    ["duration_type"] = "seconds",
    ["easeType"] = "none",
    },
    ["main"] = {
    ["type"] = "none",
    ["easeType"] = "none",
    ["easeStrength"] = 3,
    ["preset"] = "alphaPulse",
    ["duration_type"] = "seconds",
    },
    ["finish"] = {
    ["type"] = "none",
    ["easeStrength"] = 3,
    ["duration_type"] = "seconds",
    ["easeType"] = "none",
    },
    },
    ["cooldownEdge"] = false,
    ["wordWrap"] = "WordWrap",
    ["information"] = {
    ["forceEvents"] = true,
    ["ignoreOptionsEventErrors"] = true,
    },
    ["fixedWidth"] = 200,
    ["width"] = 30,
    ["alpha"] = 1,
    ["zoom"] = 0,
    ["semver"] = "1.0.0",
    ["tocversion"] = 11500,
    ["id"] = "Party 2 Is Hurt",
    ["cooldownTextDisabled"] = false,
    ["frameStrata"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["justify"] = "RIGHT",
    ["uid"] = "jNOmkEXpWC1",
    ["inverse"] = false,
    ["useCooldownModRate"] = true,
    ["shadowColor"] = {
    0,
    0,
    0,
    1,
    },
    ["conditions"] = {
    },
    ["cooldown"] = false,
    ["displayIcon"] = 134153,
    }