id: Enemy Loose
triggers:
- trigger:
    duration: '1'
    names: {}
    debuffType: HELPFUL
    type: custom
    unevent: auto
    custom: function(allstates)\n    -- Throttle the check for perf?  What is config?\n    if
      not aura_env.last or GetTime() - aura_env.last > 0.2 then\n        -- Set the
      last time\n        aura_env.last = GetTime()\n        \n        -- Start a count\n        local
      enemyIndex = 0\n        \n        -- Iterate 40 times\n        for i = 1, 40
      do\n            -- Concat string with index\n            local unit = "nameplate"..i\n            local
      isTanking, status, threatpct, rawthreatpct, threatvalue = UnitDetailedThreatSituation("player",
      unit)\n            \n            local unitCanAttack = UnitCanAttack("player",
      unit)\n            local unitAffectingCombat = UnitAffectingCombat(unit)\n            \n            if
      unitCanAttack and unitAffectingCombat and not isTanking then\n                enemyIndex
      = enemyIndex + 1\n            end\n        end\n        \n        if enemyIndex
      > 0 then\n            allstates[""] = allstates[""] or {show = true}\n            allstates[""].show
      = true\n            allstates[""].changed = true\n        else\n            allstates[""]
      = allstates[""] or {show = false}\n            allstates[""].show = false\n            allstates[""].changed
      = true\n        end\n        \n        return true\n    end\nend
    subeventSuffix: _CAST_START
    event: Health
    customStacks: function() return aura_env.count end\n
    unit: player
    custom_type: stateupdate
    spellIds: {}
    use_unit: true
    check: update
    use_absorbMode: true
    subeventPrefix: SPELL
    customVariables: '{\n  stacks = true,\n}'
  untrigger: {}
regionType: icon
position:
  xOffset: 435.5000447591146
  yOffset: -135.5600015258789
  anchorPoint: CENTER
  frameStrata: 1
visual:
  regionType: icon
  color:
  - 0.9921569228172302
  - 1
  - 0.988235354423523
  - 1
  desaturate: false
  alpha: 1
  cooldown: false
  glow: false
parent: Power, Health and Enemy Details
load:
  use_never: false
  talent: {}
  size: {}
  spec: {}
  class:
    single: WARRIOR
    multi:
      WARRIOR: true
  zoneIds: ''
actions:
  init:
    custom: ''
    do_custom: false
animation:
  start:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
  main:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
  finish:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
