id: Enemy In Melee Range
triggers:
- trigger:
    type: unit
    subeventSuffix: _CAST_START
    event: Range Check
    use_unit: true
    range: '5'
    unit: target
    spellIds: {}
    use_range: true
    names: {}
    subeventPrefix: SPELL
    range_operator: <=
    debuffType: HELPFUL
  untrigger: {}
regionType: icon
position:
  xOffset: 495.4265893554689
  yOffset: -165.633331044515
  anchorPoint: CENTER
  frameStrata: 1
visual:
  regionType: icon
  color:
  - 1
  - 1
  - 1
  - 1
  desaturate: false
  alpha: 1
  cooldown: true
  glow: false
parent: Power, Health and Enemy Details
load:
  use_never: false
  talent: {}
  class: {}
  spec: {}
  size: {}
conditions:
- check:
    trigger: 1
    variable: show
    value: 0
  changes:
  - property: alpha
- check:
    trigger: 1
    variable: show
    value: 1
  changes:
  - value: 1
    property: alpha
actions: {}
animation:
  start:
    type: none
    easeStrength: 3
    duration_type: seconds
    easeType: none
  main:
    type: none
    easeStrength: 3
    duration_type: seconds
    easeType: none
  finish:
    type: none
    easeStrength: 3
    duration_type: seconds
    easeType: none
