id: Health Below 50
triggers:
- trigger:
    type: unit
    subeventSuffix: _CAST_START
    use_showCost: true
    use_power: false
    event: Health
    use_percentpower: false
    names: {}
    powertype: 3
    spellIds: {}
    subeventPrefix: SPELL
    use_unit: true
    unit: player
    use_powertype: true
    debuffType: HELPFUL
  untrigger: {}
regionType: icon
position:
  xOffset: 645.0333129882813
  yOffset: -165.600015258789
  anchorPoint: CENTER
  frameStrata: 1
visual:
  regionType: icon
  color:
  - 1
  - 1
  - 1
  - 1
  desaturate: false
  alpha: 1
  cooldown: false
  glow: false
parent: Power, Health and Enemy Details
load:
  use_never: false
  talent: {}
  spec: {}
  class:
    single: ROGUE
    multi:
      ROGUE: true
  size: {}
conditions:
- check:
    trigger: 1
    variable: percenthealth
    value: '50'
    op: '>'
  changes:
  - value:
    - 1
    - 1
    - 1
    - 0
    property: color
actions: {}
animation:
  start:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
  main:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
  finish:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
