id: Party 3 Is Hurt
triggers:
- trigger:
    debuffType: HELPFUL
    type: custom
    custom_type: stateupdate
    subeventSuffix: _CAST_START
    names: {}
    duration: '1'
    event: Health
    unit: player
    unevent: auto
    subeventPrefix: SPELL
    spellIds: {}
    custom: function(allstates)\n    if not aura_env.last or GetTime() - aura_env.last
      > 0.5 then\n        aura_env.last = GetTime()\n        \n        local numGroup
      = GetNumGroupMembers()\n        if (numGroup < 4) then\n            allstates[""]
      = allstates[""] or {show = false}\n            allstates[""].show = false\n            allstates[""].changed
      = true\n            return true\n        end\n        \n        local hp,hpMax
      = UnitHealth("party3"),UnitHealthMax("party3")\n        \n        if (math.ceil((hp
      / hpMax) * 100) <= 60 and not UnitIsDead("party3")) then\n            allstates[""]
      = allstates[""] or {show = true}\n            allstates[""].changed = true\n            return
      true\n        else\n            allstates[""] = allstates[""] or {show = false}\n            allstates[""].show
      = false\n            allstates[""].changed = true\n            return true\n        end\n    end\nend\n\n\n\n
    check: update
    use_unit: true
    custom_hide: timed
    customVariables: '{}'
  untrigger:
    custom: function()\n    return not aura_env.isTriggered\nend
regionType: icon
position:
  xOffset: 525.3809971400667
  yOffset: -150.5749938964844
  anchorPoint: CENTER
  frameStrata: 1
visual:
  regionType: icon
  color:
  - 0.96470588235294
  - 0.89803921568627
  - 0.91764705882353
  - 1
  desaturate: false
  alpha: 1
  cooldown: false
  glow: false
parent: Power, Health and Enemy Details
load:
  use_level: false
  talent: {}
  level_operator:
  - ~=
  use_spellknown: false
  zoneIds: ''
  spec: {}
  use_never: false
  level:
  - '120'
  class:
    single: WARLOCK
    multi:
      WARLOCK: true
  size: {}
actions: {}
animation:
  start:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
  main:
    type: none
    easeType: none
    easeStrength: 3
    duration_type: seconds
    preset: alphaPulse
  finish:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
