id: Player is moving
triggers:
- trigger:
    itemName: 0
    use_genericShowOn: true
    genericShowOn: showOnCooldown
    subeventPrefix: SPELL
    debuffType: HELPFUL
    use_spec: true
    use_track: true
    names: {}
    use_message: false
    spellName: 5176
    instance_size: {}
    use_sourceName: false
    use_inverse: false
    use_targetRequired: false
    subeventSuffix: _CAST_START
    use_itemName: true
    use_moveSpeed: false
    event: Conditions
    realSpellName: Wrath
    use_spellName: true
    spellIds: {}
    type: unit
    use_ismoving: true
    use_unit: true
    use_messageType: false
    unit: target
  untrigger: {}
regionType: icon
position:
  xOffset: 615.0237322126118
  yOffset: -135.5999862670899
  anchorPoint: CENTER
  frameStrata: 1
visual:
  regionType: icon
  color:
  - 1
  - 1
  - 1
  - 1
  desaturate: false
  alpha: 1
  cooldown: true
  glow: false
parent: Power, Health and Enemy Details
load:
  use_never: false
  talent: {}
  class: {}
  spec: {}
  size: {}
actions: {}
animation:
  start:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
  main:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
  finish:
    easeStrength: 3
    type: none
    duration_type: seconds
    easeType: none
