id: Target Is Moving
triggers:
- trigger:
    customVariables: '{}'
    type: custom
    custom_hide: timed
    custom_type: stateupdate
    names: {}
    duration: '1'
    event: Health
    unit: player
    unevent: auto
    custom: function(allstates)\n    if not aura_env.last or GetTime() - aura_env.last
      > 0.5 then\n        aura_env.last = GetTime()\n        \n        local unitSpeed,
      _, _, _ = GetUnitSpeed("target")           \n        if not unitSpeed then return
      end\n        \n        if unitSpeed > 0 then\n            allstates[""] = allstates[""]
      or {show = true}\n            allstates[""].changed = true\n            return
      true\n        else\n            allstates[""] = allstates[""] or {show = false}\n            allstates[""].show
      = false\n            allstates[""].changed = true\n            return true\n        end\n    end\nend\n\n\n\n
    spellIds: {}
    subeventPrefix: SPELL
    check: update
    use_unit: true
    subeventSuffix: _CAST_START
    debuffType: HELPFUL
  untrigger: {}
regionType: icon
position:
  xOffset: 645.0165893554688
  yOffset: -150.6124938964844
  anchorPoint: CENTER
  frameStrata: 1
visual:
  regionType: icon
  color:
  - 0.96470588235294
  - 0.89803921568627
  - 0.91764705882353
  - 1
  desaturate: false
  alpha: 1
  cooldown: false
  glow: false
parent: Power, Health and Enemy Details
load:
  use_level: false
  talent: {}
  level_operator:
  - ~=
  size: {}
  spec: {}
  use_never: false
  level:
  - '120'
  class:
    single: WARLOCK
    multi:
      WARLOCK: true
  zoneIds: ''
actions: {}
animation:
  start:
    type: none
    easeStrength: 3
    duration_type: seconds
    easeType: none
  main:
    type: none
    easeType: none
    easeStrength: 3
    preset: alphaPulse
    duration_type: seconds
  finish:
    type: none
    easeStrength: 3
    duration_type: seconds
    easeType: none
