{
    ["sparkWidth"] = 10,
    ["iconSource"] = -1,
    ["xOffset"] = 322,
    ["adjustedMax"] = "",
    ["adjustedMin"] = "",
    ["yOffset"] = -146,
    ["anchorPoint"] = "CENTER",
    ["sparkRotation"] = 0,
    ["sparkRotationMode"] = "AUTO",
    ["actions"] = {
        ["start"] = {},
        ["finish"] = {},
        ["init"] = {},
    },
    ["triggers"] = {
        {
            ["trigger"] = {
                ["use_showAbsorb"] = true,
                ["type"] = "unit",
                ["use_absorbHealMode"] = true,
                ["subeventSuffix"] = "_CAST_START",
                ["use_absorbMode"] = true,
                ["event"] = "Health",
                ["subeventPrefix"] = "SPELL",
                ["use_showIncomingHeal"] = true,
                ["spellIds"] = {},
                ["use_unit"] = true,
                ["unit"] = "player",
                ["names"] = {},
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {},
        },
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        1,
        1,
        1,
        1,
    },
    ["internalVersion"] = 78,
    ["progressSource"] = {
        -1,
        "",
    },
    ["selfPoint"] = "CENTER",
    ["text"] = false,
    ["barColor"] = {
        0,
        0,
        1,
        1,
    },
    ["desaturate"] = false,
    ["sparkHidden"] = "NEVER",
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        {
            ["type"] = "subforeground",
        },
        {
            ["type"] = "subbackground",
        },
    },
    ["gradientOrientation"] = "HORIZONTAL",
    ["textureSource"] = "LSM",
    ["load"] = {
        ["talent"] = {
            ["multi"] = {},
        },
        ["spec"] = {
            ["multi"] = {},
        },
        ["class"] = {
            ["multi"] = {},
        },
        ["size"] = {
            ["multi"] = {},
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = false,
    ["backgroundColor"] = {
        0,
        0,
        1,
        1,
    },
    ["information"] = {},
    ["sparkOffsetX"] = 0,
    ["icon"] = false,
    ["smoothProgress"] = true,
    ["useAdjustededMin"] = false,
    ["regionType"] = "aurabar",
    ["animation"] = {
        ["start"] = {
            ["easeStrength"] = 3,
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["easeStrength"] = 3,
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["easeStrength"] = 3,
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["config"] = {},
    ["icon_side"] = "RIGHT",
    ["uid"] = "345WbRL7y2Q",
    ["sparkHeight"] = 30,
    ["texture"] = "Solid",
    ["anchorFrameType"] = "SCREEN",
    ["sparkTexture"] = "InterfaceCastingBarUI-CastingBar-Spark",
    ["spark"] = false,
    ["alpha"] = 1,
    ["id"] = "Health2",
    ["enableGradient"] = false,
    ["frameStrata"] = 1,
    ["width"] = 5,
    ["zoom"] = 0,
    ["sparkColor"] = {
        1,
        1,
        1,
        1,
    },
    ["inverse"] = false,
    ["height"] = 5,
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {},
    ["barColor2"] = {
        0,
        0,
        1,
        1,
    },
    ["authorOptions"] = {},
}