{
    ["sparkWidth"] = 10,
    ["iconSource"] = -1,
    ["xOffset"] = 322,
    ["adjustedMax"] = "",
    ["adjustedMin"] = "",
    ["yOffset"] = -152,
    ["anchorPoint"] = "CENTER",
    ["sparkRotation"] = 0,
    ["sparkRotationMode"] = "AUTO",
    ["backgroundColor"] = {
        0,
        0,
        1,
        1,
    },
    ["triggers"] = {
        {
            ["trigger"] = {
                ["type"] = "custom",
                ["subeventSuffix"] = "_CAST_START",
                ["debuffType"] = "HELPFUL",
                ["event"] = "Health",
                ["subeventPrefix"] = "SPELL",
                ["unit"] = "player",
                ["names"] = {},
                ["custom"] = "function(allstates)\n    -- Throttle the check for perf?  What is config?\n    if not aura_env.last or GetTime() - aura_env.last > 0.2 then\n        -- Set the last time\n        aura_env.last = GetTime()\n        \n        -- Start a count\n        local enemyIndex = 0\n        \n        -- Check if pet exists\n        local petExists = UnitExists(\"pet\")\n        \n        if petExists then\n            allstates[\"\"] = allstates[\"\"] or {show = true}\n            allstates[\"\"].show = true\n            allstates[\"\"].changed = true\n        else\n            allstates[\"\"] = allstates[\"\"] or {show = false}\n            allstates[\"\"].show = false\n            allstates[\"\"].changed = true\n        end\n        \n        return true\n    end\nend\n\n\n",
                ["custom_type"] = "stateupdate",
                ["check"] = "update",
                ["spellIds"] = {},
                ["events"] = "UNIT_PET, PLAYER_ENTERING_WORLD",
                ["custom_hide"] = "timed",
            },
            ["untrigger"] = {},
        },
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        1,
        1,
        1,
        1,
    },
    ["internalVersion"] = 78,
    ["progressSource"] = {
        -1,
        "",
        100,
    },
    ["selfPoint"] = "CENTER",
    ["barColor"] = {
        0,
        0,
        1,
        1,
    },
    ["desaturate"] = false,
    ["id"] = "Pet Active",
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        {
            ["type"] = "subbackground",
        },
        {
            ["type"] = "subforeground",
        },
    },
    ["height"] = 5,
    ["textureSource"] = "LSM",
    ["load"] = {
        ["talent"] = {
            ["multi"] = {},
        },
        ["spec"] = {
            ["multi"] = {},
        },
        ["class"] = {
            ["multi"] = {},
        },
        ["size"] = {
            ["multi"] = {},
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = false,
    ["alpha"] = 1,
    ["information"] = {},
    ["authorOptions"] = {},
    ["actions"] = {
        ["start"] = {},
        ["finish"] = {},
        ["init"] = {},
    },
    ["smoothProgress"] = true,
    ["useAdjustededMin"] = false,
    ["regionType"] = "aurabar",
    ["sparkColor"] = {
        1,
        1,
        1,
        1,
    },
    ["animation"] = {
        ["start"] = {
            ["easeStrength"] = 3,
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["easeStrength"] = 3,
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["easeStrength"] = 3,
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["icon_side"] = "RIGHT",
    ["uid"] = "vL0IYmMBail",
    ["sparkHeight"] = 30,
    ["texture"] = "Solid",
    ["width"] = 5,
    ["sparkTexture"] = "InterfaceCastingBarUI-CastingBar-Spark",
    ["spark"] = false,
    ["zoom"] = 0,
    ["sparkHidden"] = "NEVER",
    ["sparkOffsetX"] = 0,
    ["frameStrata"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["gradientOrientation"] = "HORIZONTAL",
    ["config"] = {},
    ["inverse"] = false,
    ["enableGradient"] = false,
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {},
    ["barColor2"] = {
        0,
        0,
        1,
        1,
    },
    ["icon"] = false,
}